### ISSUE TITLE
gt_image.txt should contain which type of information.

### ISSUE THREAD

**Issue by indiefool** [kurapan/EAST#39]

**Comment by indiefool** [comment]
> _No description provided._

cause i just converted the xml file directly into txt but it when i started training it ,it got stuck in one epoch.........
any help.... what i am thinking is should it only contain coordinates or what?
please reply fast i have a project to complete by 22nd ...........

**Comment by indiefool** [comment]
will be thankful if someone provide me with an example

**Comment by kurapan** [comment]
This is an example of how an annotation file of one image should look like.
```
﻿377,117,463,117,465,130,378,130,Genaxis Theatre
493,115,519,115,519,131,493,131,[06]
374,155,409,155,409,170,374,170,###
492,151,551,151,551,170,492,170,62-03
376,198,422,198,422,212,376,212,Carpark
494,190,539,189,539,205,494,206,###
374,1,494,0,492,85,372,86,###
```
There are 8 numbers seperated by commas that represent the coordinates of bounding boxes and the last value on each row is the text in that bounding box. Illegible text is substituted by three hashes and isn't considered when calculating loss during training. If you only have bounding box coordinates, you either have to modify the annotation files to add some random text (the text itself isn't used so it can be literally anything) or you have to modify the code that prepares data and add some random text there or even change it so that it doesn't require text values.

**Comment by indiefool** [comment]
one more thing when i annotated my dataset i only got 4 coordinates,
how to get 8 coordinates,should i have to annotate it again?
i used labelimg for annotation

**Comment by indiefool** [comment]
those 4 coordinates include xmax , xmin,ymax,ymin

**Comment by indiefool** [comment]
ohkk. got the solution.Thanks.
