### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by jhaggle** [kurapan/EAST#45]
Could you explain the following terms:

geo_maps
score_maps
image_fns
geo_map_channels
overly_small_text_region_training_mask
text_region_boundary_training_mask

**Comment by CattleOfRa** [comment]
Yes, please someone help to explain the above terminology. Thanks

**Comment by jhaggle** [comment]
Yes, you should really explain your code better.

**Comment by kurapan** [comment]
geo_maps: The maps (channels) that represent the geometry maps in the EAST algorithm. It's the distances to the top, right, bottom, and left edge of the bounding box from any given point within the bounding box.
score_maps: This just represents whether a point belongs to a text region or not. For ground truth, this is binary. The predicted maps are in [0; 1] range.
image_fns: Filenames of images in the dataset.
geo_map_channels: Number of geometry map channels.
overly_small_text_region_training_mask: Binary mask of text regions that are too small and deemed insignificant in training. If I remember correctly, the loss isn't counted on these points because we don't require the model to learn to find those small text regions because it's very difficult but we don't want to penalize it in case it found some of these regions either.
text_region_boundary_training_mask: It's the area around the edge of the bounding boxes. The ground truth bounding boxes in the EAST algorithm are smaller than the actual text region annotations, so this can be represented as: TEXT_REGION_BBOX - GROUND_TRUTH_BBOX.

**Comment by jhaggle** [comment]
Thank you, after some more scrutinizing I realized most of this.
My own notes:
score_map - Zero except where there is a polygon.
geo_map - five dimensional and shows the distance from a point in a polygon to the the left, right, upper and bottom egdes of the polygon. (Rectangular polygon :p)
Overly_small_text_region_training_mask - Covers polygons that are to small, and excludes them from the traingen. (However, something strange about polygons with tags. Those are excluded to, that should not be the case. Only polygons without a tag - only * or ### - should be excluded. If Text_region_boundary_training_mask - A frame around a text square. That area is somewhat uncertain and is therefore excluded.
