### ISSUE TITLE
overly_small_text_region_training_mask

### ISSUE THREAD

**Issue by jhaggle** [kurapan/EAST#46]
If some the text in an image is to small, it is excluded from the training by this piece of code:
`
 if min(poly_h, poly_w) < FLAGS.min_text_size:
            cv2.fillPoly(overly_small_text_region_training_mask, poly.astype(np.int32)[np.newaxis, :, :], 0) 
`

However, the same text is excluded also if "tag" is true. WHY? 
`
if tag:
            cv2.fillPoly(overly_small_text_region_training_mask, poly.astype(np.int32)[np.newaxis, :, :], 0)
`

**Comment by kurapan** [comment]
In ICDAR datasets, some text region bounding boxes that are too small don't have a label with the word that appears there. Sometimes it's not even legible to a human, sometimes it's legible to a human but deemed insignificant due to the size. Such bounding boxes have a special label, either '*' or '###'. So this here is two different conditions depending on the size of the text. The first one depends on the actual size of the bounding box, the second one depends on the annotation of the dataset.

**Comment by jhaggle** [comment]
Yes, I get what you say. HOWEVER, as the code is written you do not skip boxes with  either '*' or '###, instead you skip boxes that actually has a tag containing text.

**Comment by kurapan** [comment]
It doesn't skip anything. The tag is True if the label is '*' or '###' and in that case it adds it to the mask of the small regions.

**Comment by jhaggle** [comment]
What I mean by "skip" is certain parts of the image is skipped during the training. This includes for exemple the text_region_boundary_mask. The border around the image is not used in training since it is ambiguous. It is neither right nor wrong. In the same way, text boxes with the label ### are USED in the training, while text boxes containing text is actually skipped.
